SED_EXPRV =

SED_EXPRV += -e 's=@@SHINIT_THINGS_BASEDIR@@=${SHINIT_THINGS_BASEDIR}=g'
SED_EXPRV += -e 's=@@SHINIT_THINGS_LOCALDIR@@=${SHINIT_THINGS_LOCALDIR}=g'

SED_EXPRV += -e 's=@@GIT_EDITOR@@=${GIT_EDITOR}=g'

RUN_SED_EDIT = sed -r ${SED_EXPRV}
